apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ratings-web
  labels:
    app: ratings-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: ratings-web
    servicePort: 80