name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'infra-azurestack-seattle-vg' # for stage Seattle

stages:

# Deploy AKS Engine
- stage: aksengine_seattle
  displayName: 'Deploy AKS Engine (Seattle)'
  dependsOn: []

  pool:
    name: $(agentPool)
    vmImage: ubuntu-latest

  variables: 
  - group: 'infra-azurestack-seattle-vg' # environment specific variable group

  jobs:
  - template: templates/infra.azurestack.template.yaml
    parameters: 
      azureServiceConnection: '$(azureServiceConnection)' # azure subscription 
      azureLocation: '$(location)' # Azure (Stack) Location
      workingDirectory: 'src/tf/aksengine' # working dir
      tfKey: 'seattle.tfstate' # state filename
      tfAzureServiceConnection: '$(azureServiceConnection)'
      tfVersion: '$(tfVersion)' # TF version