kind: PersistentVolumeClaim
apiVersion: v1
metadata:  
  name: mssql-data
spec:
  storageClassName: {{ .Values.mssql.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mssql.pvcClaim.size }}